# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MailPlus Automation Test
on:
  workflow_dispatch:
    inputs:
      typeOfTesting:
        type: choice
        description: Select Type of Test
        default: "wdio.web"
        required: true
        options:
          - wdio.mob
          - wdio.web
          - wdio.web.bs
      bsUserName:
        description: "BrowserStack Username"
        required: true
        type: string
      bsUserKey:
        description: "BrowserStack Key"
        required: true
        type: string
      bsAppPath:
        description: "Set BrowserStack app path {Note: If you run app then set this}"
        required: false
        type: string

jobs:
  WebdriverIO-Automation:
    runs-on: ubuntu-latest
    steps:
      - name: Selection of Testing type
        run: |
          echo "Suite Name: ${{ github.event.inputs.typeOfTesting == '' && github.event.inputs.typeOfTesting  || 'wdio.web' }} "
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Install
        run: npm install
      - name: Test
        run: |
          BSUSERNAME=${{ github.event.inputs.bsUserName }} BSKEY=${{ github.event.inputs.bsUserKey }} BSAPPPATH=${{ github.event.inputs.bsAppPath }} npm run ${{ github.event.inputs.typeOfTesting == '' && github.event.inputs.typeOfTesting  || 'wdio.web' }}
